page:
    resource: "@PageBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
post:
    resorce: '@PostBundle/Resources/config/routing.yml'
